-- 1030300's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Hollow Knight: Silksong
-- Generated: 2025-09-04 20:21:40
-- Total Depots: 3
-- Total DLCs: 0

-- MAIN APPLICATION
addappid(1030300) -- Hollow Knight: Silksong
-- MAIN APP DEPOTS
addappid(1030301, 1, "f4a253f96969f93b8a9392cddf6f1b779886ea10a160e7ca148b92bae09abd28") -- Depot 1030301
setManifestid(1030301, "3229726349000518284", 8116341853)
addappid(1030302, 1, "bc736fb6e74601f627b4890559822b4b8e786e36e949b881dcd25419e8a15e9e") -- Depot 1030302
setManifestid(1030302, "1365730835793684614", 8169573476)
addappid(1030303, 1, "ea761f41bd28ae29fd22375e81702eadc64796099fd9dcf01ea2a190536cc7c3") -- Depot 1030303
setManifestid(1030303, "8384590172287463475", 8134687634)