-- 1669480's Lua and Manifest Generated by Solus Bot in Morrenus Games!
-- Firefighting Simulator: Ignite
-- Generated: 2025-09-09 17:50:59
-- Total Depots: 5
-- Total DLCs: 1 (2 excluded)
-- Shared Depots: 2

-- MAIN APPLICATION
addappid(1669480) -- Firefighting Simulator: Ignite
-- MAIN APP DEPOTS
addappid(1669481, 1, "86379ba94d829db600d16fb1a8228f1311045edc0905cd7f55c8e674028ce2e8") -- Depot 1669481
setManifestid(1669481, "7364847499108013897", 38254575964)
addappid(3697660, 1, "7a1b1c50379f373233659c2752efbd243877e437a08464c12dd718be2496e83b") -- Depot 3697660
setManifestid(3697660, "7677613033911163998", 0)
-- SHARED DEPOTS (from other apps)
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853") -- VC 2022 Redist (Shared from App 228980)
setManifestid(228989, "3514306556860204959", 39590283)
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8") -- DirectX Jun 2010 Redist (Shared from App 228980)
setManifestid(228990, "1829726630299308803", 102931551)
-- DLCS WITH DEDICATED DEPOTS
-- Firefighting Simulator Ignite - Rosenbauer HEROS Titan DLC  (AppID: 3544160)
addappid(3544160)
addappid(3544160, 1, "907cfcb846ccb3902d350463e48db5bb1b98ec8850923efc377194340541da16") -- Firefighting Simulator Ignite - Rosenbauer HEROS Titan DLC  - Depot 3544160
setManifestid(3544160, "8779044660461313785", 0)
-- EXCLUDED DLCS:
-- UNRELEASED DLCS (COMMENTED OUT)
-- addappid(3697660) -- DLC 3697660 (unreleased)
-- addappid(3707380) -- DLC 3707380 (unreleased)